import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Ainsfluu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex min-h-screen items-center justify-center bg-zinc-50 font-sans dark:bg-black">
        <Providers>
          <SidebarProvider
            style={
              {
                "--sidebar-width": "12rem",
                "--sidebar-width-mobile": "12rem",
              } as React.CSSProperties
            }
          >
            <AppSidebar />
            <main className="p-5 w-full space-y-2">
              <SidebarTrigger />
              {children}
            </main>
          </SidebarProvider>
        </Providers>
      </body>
    </html>
  );
}
